apiVersion: v1
kind: Pod
metadata:
  name: tiger
  namespace: tiger
spec:
  containers:
  - image: alpain:3.22
    name: main
    args:
    - /bin/sh
    - -c
    - sleep 60; touch /tmp/healthy; sleep 86400
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5