apiVersion: v1
kind: Pod
metadata:
  name: listener
  namespace: translate
  labels:
    app: hw
spec:
  containers:
  - image: shekeriev/k8s-listener
    name: listener
    ports:
    - containerPort: 5000