apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apple-access
  namespace: apple
spec:
  podSelector: {} # all pods in apple namespace
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: orange
