apiVersion: v1
kind: Pod
metadata:
  name: pod205
spec:
  nodeSelector: # add new block
    exam: fast # use requested label
  containers:
  - image: alpine
    name: main
    args:
    - /bin/sh
    - -c
    - sleep 86400