apiVersion: v1
kind: Pod
metadata:
  name: pod206
spec:
  nodeName: jupiter-2 # add row with name of requested node name
  containers:
  - image: alpine
    name: main
    args:
    - /bin/sh
    - -c
    - sleep 86400