apiVersion: v1    # new row
kind: Namespace   # new row
metadata:         # new row
  name: cherry    # new row
---
apiVersion: v1
kind: Pod
metadata:
  name: t208
  namespace: cherry
  labels:         # add labels block
    app: cherry   # add kvp
spec:
  containers:
  - image: shekeriev/k8s-environ
    name: main
    env:
    - name: FRUIT
      value: "Did you know that cherries are red and tasty? :)"
    - name: FOCUSON
      value: "FRUIT"
---
apiVersion: v1          # new row
kind: Service           # new row
metadata:               # new row
  name: cherry-svc      # new row
  namespace: cherry     # new row          
spec:                   # new row
  type: NodePort        # new row        
  selector:             # new row  
    app: cherry         # new row
  ports:                # new row
    - port: 80          # new row      
      targetPort: 80    # new row            
      nodePort: 32208   # new row            