apiVersion: v1
kind: LimitRange
metadata:
  name: projectx-limits
  namespace: projectx
spec:
  limits:
  - type: Pod
    max:
      cpu: "2000m"
      memory: "1.5Gi"
    min:
      cpu: "100m"
      memory: "100Mi"
  - type: Container
    default:
      cpu: "200m"
      memory: "128Mi"
    max:
      cpu: "1000m"
      memory: "750Mi"
    min:
      cpu: "50m"
      memory: "64Mi"
      