apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devguru
  namespace: projectx
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "deployments", "replicasets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devguru-binding
  namespace: projectx
subjects:
- kind: Group
  name: gurus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io

