apiVersion: v1
kind: Namespace
metadata:
  name: cherry
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cherry
  namespace: cherry
spec:
  hard:
    pods: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry
  namespace: cherry
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cherry
  template:
    metadata:
      labels:
        app: cherry
    spec:
      containers:
      - image: alpain:3.22
        name: main
        args:
        - /bin/sh
        - -c
        - sleep 86400