apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  index.html: |
    <h1>{{ .Values.indexFile }}</h1>
    <img src="data:image/png;base64,{{ .Files.Get "pictures/nginx.png" | b64enc }}" alt="nginx">