# 01-homework-ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: homework
---
# 02-homework-1-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: homework-1
  namespace: homework
  labels:
    app: hw
spec:
  containers:
    - name: app
      image: shekeriev/k8s-oracle
      ports:
        - containerPort: 5000
---
# 03-homework-2-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: homework-2
  namespace: homework
  labels:
    app: hw
spec:
  containers:
    - name: app
      image: shekeriev/k8s-oracle
      ports:
        - containerPort: 5000
---
# 04-homework-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  namespace: homework
spec:
  selector:
    app: hw
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 5000
  type: NodePort
