apiVersion: v1
kind: Pod
metadata:
  name: homework-1
  namespace: homework
  labels:
    app: hw
  annotations:
    purpose: homework
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-1
    ports:
    - containerPort: 5000
