apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  namespace: homework
spec:
  selector:
    app: hw
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 5000  
  type: NodePort